[package]
name = "fit-activities-rerun"
version = "0.1.0"
edition = "2024"
# Reminder: Always keep `channel` in `rust-toolchain.toml` in sync with `rust-version`.
rust-version = "1.92.0"
authors = ["Jens Krause <jkrause.io>"]
description = "Visualize `FIT` activity data in Rerun.io"
license = "MIT"
homepage = "https://github.com/sectore/fit-activities-rerun"
repository = "https://github.com/sectore/fit-activities-rerun"
keywords = ["fit", "rerun"]
categories = ["command-line-utilities"]
exclude = [
    ".github/*",
    "result/*",
]

[dependencies]
# rerun = { version = "0.28.1", default-features = false, features = [
#     "sdk",
#     "map_view",
#     "server",
#     "clap"
# ] }
rerun = { git = "https://github.com/sectore/rerun", branch = "blueprint-rs", default-features = false, features = [
    "sdk",
    "map_view",
    "server",
    "clap"
] }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
fitparser = "0.10.0"
dotenvy = "0.15"
